version: '3'

services:
  web:
    container_name: numerosExtenso
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/numerosExtenso
    ports:
      - "8000:8000"